### PR TITLE
Add build action

### PR DESCRIPTION
**Pull request by kgrubb**
This includes the appstream validation, but adds it after a build is completed.

Supersedes https://github.com/elementary/actions/pull/38.

I've also got to test this pr out too, right now its just a rough draft

### CODE REVIEW

**Comment by kgrubb** [comment]
Alright, tested it out here:

https://github.com/kgrubb/helloworld/runs/593985392

**Comment by kgrubb** [comment]
One thing to note is that this currently requires a data dir with the appdata.xml inside to be built into the `build` directory.

**Comment by danirabbit** [comment]
Yeah that’s one reason to do it from packaging is so that you can uncompress the package at the end and always have consistent locations for the files you need to test

**Comment by decathorpe** [comment]
> Yeah that’s one reason to do it from packaging is so that you can uncompress the package at the end and always have consistent locations for the files you need to test

You don't necessarily need to do it from packaging. Since I've added a `meson install` step to most elementary project's CI settings (:smiling_imp:) it would be easy to just test DESTDIR contents after the install (where the location of installed appdata is then predictable).

**Comment by decathorpe** [comment]
Looking at the shell script, you don't need to use `find` at all.

Something like this should work:

```
appstream-util validate-relax build/out/usr/share/metainfo/*.appdata.xml
appstreamcli validate build/out/usr/share/metainfo/*.appdata.xml
```

This only covers appdata files *with* translations, only *after* they have been processed in `meson install`, and only looks for them in the standard location.

**Comment by jeremypw** [comment]
@kgrubb Is this ready for review? Maybe better to request a particular reviewer or team as there has been no action for a while. Unfortunately, I do not have enough knowledge to do it.

**Comment by kgrubb** [comment]
I think this can be closed. We ended up going a different direction, and with flatpaks becoming more of the norm, a build step is no longer really necessary.

**Pull request closed without merging**
