### PR TITLE
Add git environment variables

### PR DESCRIPTION
**Pull request by kgrubb**
This PR allows people to set custom tokens, usernames, and emails via the `GIT_USER_TOKEN`, `GIT_USER_NAME`, and `GIT_USER_EMAIL` environment variables.

### CODE REVIEW

**Comment by btkostner** [comment]
I think we should add a `GIT_USER_TOKEN` env var instead of overwriting the `GITHUB_TOKEN`. That way any other actions can still use the default `GITHUB_TOKEN` variable and _only_ this workflow would be different.

**Comment by kgrubb** [comment]
Should I make the github actions user the default username/email combo and require elementary projects to set the following env vars?

`GIT_USER_TOKEN`
`GIT_USER_NAME`
`GIT_USER_EMAIL`

**Comment by btkostner** [comment]
@kgrubb That sounds best!

**Review by btkostner — APPROVED** [review]
This looks good but I have not ran to test

**Comment by kgrubb** [comment]
Here's where i've been testing:
https://github.com/kgrubb/helloworld/runs/270557726

here's the updated release file example: https://github.com/kgrubb/helloworld/blob/master/.github/workflows/release.yml

and here you can see that my personal user account was used instead of the github actions account: https://github.com/kgrubb/helloworld/releases/tag/1.4.0


here's the branch protection rule's i tested with:

Screenshot from 2019-10-22 16-45-15

**Pull request merged**
