### PR TITLE
add appstream validator action

### LINKED ISSUE #37: Provide AppStream validation
Much like the lint action, it would be handy to provide an AppStream data validation action so we can ensure things are valid before they're merged. Would avoid issues with malformed AppData, missing tags, etc.

### PR DESCRIPTION
**Pull request by kgrubb**
Still need to test this one out, but the manual commands work so far. I'll report back with some links once I've tested out the action on a fake package.

Fixes #37

### CODE REVIEW

**Comment by decathorpe** [comment]
It would be great if the action could run both the appstream and the appstream-glib validators.

- appstream-util (appstream-glib): `appstream-util validate-relax --nonet PATH`
- appstreamcli (appstream): `appstreamcli validate --no-net PATH`

As mentioned in the linked issue, elementary and KDE use appstream, everybody else (GNOME / Packagekit, etc) uses appstream-glib.

---

However, with the way you're currently setting up this action, it will run against **unprocessed** appdata files (named `appdata.xml.in` files most often - the `*appdata*` glob covers those too), which might not be valid until they get processed by gettext during a meson install.

The only way to make sure the "final" version of an `.appdata.xml` file is getting validated would be after running `meson install` - and if you're doing that, it could be part of the main CI anyway (where meson install is run for almost all packages now).

**Comment by decathorpe** [comment]
Also, I'm not sure if the test environment has internet access. If it does, you could drop the `--no-net` / `--nonet` flags - then the validator also checks if screenshot URLs and such are valid links.

**Comment by kgrubb** [comment]
This makes me re-evaluate this action a bit then. I'm thinking maybe the better route is to create a generic "build" action that can handle the meson building for elementary's projects, and then this just gets incorporated into the build action? That'd keep all of the meson install steps uniform, and we would be able to update general build config in one place.

**Comment by kgrubb** [comment]
closing in favor of #39

**Pull request closed without merging**
